---
- name: Reset Switch Port using server as lookup in CMDB
  hosts: "{{ servers[server].switch }}"
  become: true
  vars_files:
  - files/cmdb.yml
  
  tasks:
  - name: Reset port "{{ servers[server].port }} on switch {{ servers[server].switch }}"
    community.general.nmcli:
      conn_name: "port{{ servers[server].port }}"
      state: up
