---
#- name: Reset network port, input server name
#  hosts: localhost
#  vars_files:
#  - files/cmdb.yml
#
#  tasks:
#  - name: lookup switch and port from CMDB to inventory
#    add_host:
#      name: "servers[server].switch"
#
- name: Reset port "{{ servers[server].port }} on switch {{ servers[server].switch }}"
  hosts: "{{ servers[server].switch }}"
  vars_files:
  - files/cmdb.yml
  
  tasks:
  - name: Reset Switch Port
    community.general.nmcli:
      conn_name: "port{{ servers[server].port }}"
      state: up
