---
- name: Reset network port, input server name
  hosts: all
  become: true
  vars_files:
  - files/cmdb.yml
  vars:
  - server: server12

  tasks:
  - name: determine switch and port
    ansible.builtin.debug:
      msg: "switch: {{ servers.{{ server }}.switch }}"
  - name: Reset Switch port
    community.general.nmcli:
      conn_name: "port6"
      state: up
